columns:
  brand_loyalty_score_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  impulse_buying_score_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  social_media_influence_score_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  exercise_frequency_per_week_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  stress_from_financial_decisions_level_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  overall_stress_level_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  sleep_quality_level_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  physical_activity_level_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  mental_health_score_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  coupon_usage_frequency_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  impulse_purchases_per_month_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  browse_to_buy_ratio_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  return_frequency_per_year_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  return_rate_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  checkout_abandonments_per_month_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  purchase_conversion_rate_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  app_usage_frequency_per_week_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  notification_response_rate_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  social_sharing_frequency_per_year_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  cart_abandonment_rate_scaled:
    dtype: Int64
    not_null: True
    required: True
    min: 0
    max: 1
  review_writing_frequency_per_year_scaled:
    dtype: Int64
    not_null: False
    required: True
    min: 0
    max: 1
  last_purchase_date_is_future:
    dtype: Boolean
    not_null: True
    required: True
    values: [True,False]
  age_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Early Adopters",
      "Early Career Professionals",
      "Professional Consolidation",
      "High Financial Stability",
      "Pre-Retirement",
      "Low Digital Adoption",
    ]
  household_size_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Very Small Household",
      "Small Household",
      "Medium Household",
      "Large Household",
      "Very Large Household",
    ]
  brand_loyalty_score_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Detractors",
      "Neutral",
      "Promoters",
    ]
  impulse_buying_score_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Highly Deliberate",
      "Considered Buyer",
      "Balanced Buyer",
      "Impulse-Prone",
      "Highly Impulsive",
    ]
  social_media_influence_score_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Independent",
      "Influence-Aware",
      "Highly Influenced",
    ]
  exercise_frequency_per_week_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Sedentary",
      "Lightly Active",
      "Moderately Active",
      "Highly Active",
    ]
  stress_from_financial_decisions_level_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Financially Unconcerned",
      "Financially Comfortable",
      "Financially Aware",
      "Financially Stressed",
      "Financially Overwhelmed",
    ]
  overall_stress_level_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Very Relaxed",
      "Relaxed",
      "Balanced",
      "Stressed",
      "Highly Stressed",
    ]
  physical_activity_level_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Lightly Activity",
      "Moderate Activity",
      "Intense Activity",
      "Very Intense Activity",
    ]
  referral_count_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Rare Referrer",
      "Occasional Referrer",
      "Active Referrer",
      "Advocate",
    ]
  impulse_purchases_per_month_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Non-impulsive",
      "Occasional Impulse Buyer",
      "Moderate Impulse Buyer",
      "Frequent Impulse Buyer",
    ]
  browse_to_buy_ratio_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Heavy Browser",
      "Casual Browser",
      "Considering Buyer",
      "Intentional Buyer",
      "Decisive Buyer",
    ]
  return_rate_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Rare Returner",
      "Occasional Returner",
      "Frequent Returner",
      "Heavy Returner",
    ]
  purchase_conversion_rate_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Rare Buyer",
      "Occasional Buyer",
      "Considered Buyer",
      "Frequent Buyer",
      "Power Buyer",
    ]
  app_usage_frequency_per_week_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Light User",
      "Regular User",
      "Heavy User",
    ]
  notification_response_rate_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Rarely Responsive",
      "Occasionally Responsive",
      "Responsive",
      "Highly Responsive",
    ]
  social_sharing_frequency_per_year_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Rare Sharer",
      "Occasional Sharer",
      "Frequent Sharer",
      "Heavy Sharer",
    ]
  cart_abandonment_rate_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Rare Abandoner",
      "Occasional Abandoner",
      "Frequent Abandoner",
      "Heavy Abandoner",
    ]
  review_writing_frequency_per_year_group:
    dtype: String
    not_null: True
    required: True
    values: [
      "Rare Reviewer",
      "Occasional Contributor",
      "Active Contributor",
      "Power Contributor",
    ]