actions:
  normalize:
    columns: [
      "stress_from_financial_decisions_level",
      "overall_stress_level",
      "sleep_quality_level",
      "physical_activity_level",
      "brand_loyalty_score",
      "impulse_buying_score",
      "social_media_influence_score",
      "mental_health_score",
      "impulse_purchases_per_month",
      "checkout_abandonments_per_month",
      "product_views_per_day",
      "ad_views_per_day",
      "social_sharing_frequency_per_year",
      "review_writing_frequency_per_year",
      "return_frequency_per_year",
      "travel_frequency_per_year",
      "return_rate",
      "purchase_conversion_rate",
      "notification_response_rate",
      "cart_abandonment_rate",
      "browse_to_buy_ratio",
    ]
  enrich:
      is_future_date:
        columns: [
          "last_purchase_date",
        ]
        values: [True, False]