data:
  ingestion:
    origin: "dhrubangtalukdar/e-commerce-shopper-behavior-amazonshopify-based"
    destination: "data/raw/data.parquet"
  bronze:
    origin: "data/raw/data.parquet"
    destination: "data/bronze/data.parquet"
  silver:
    parent: "data/silver/"
    origin: "data/bronze/data.parquet"
    destination: "data/silver/data.parquet"
  gold:
    origin: "data/silver/data.parquet"
    destination: 
      aggregations: "data/gold/aggregations.csv"
      descriptive: "data/gold/kpis_descriptive.csv"
      behavioral: "data/gold/kpis_behavioral.csv"
      operational: "data/gold/kpis_operational.csv"
      strategical: "data/gold/kpis_strategical.csv"
